services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app_storage:/app/app_storage
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
      - FLASK_ENV=production
    restart: unless-stopped